version: '3'
services:
  nginx:
    container_name: web
    image: nginx:stable-alpine
    ports:
      - 8888:80
    volumes:
      - ./src/:/var/www/html/
      - ./nginx.conf:/etc/nginx/conf.d/default.conf

  php:
    container_name: php-fpm
    image: php:7.1-fpm-alpine
    volumes:
      - ./src:/var/www/html/